worker_processes auto;

events {
  worker_connections 1024;
}

http {
  sendfile on;
  keepalive_timeout 65;

  log_format main '$remote_addr - $host [$time_local] "$request" '
                   '$status $body_bytes_sent "$http_referer" '
                   '"$http_user_agent"';

  access_log /var/log/nginx/access.log main;
  error_log  /var/log/nginx/error.log warn;

  include /etc/nginx/conf.d/*.conf;
}
